stage('Pruebas') {
            steps {
                bat 'mvn test'
            }
        }
        stage('Empaquetar') {
            steps {
                bat 'mvn package'
            }
        }
    }
    post {
        success {
            echo 'La compilacion y las pruebas fueron exitosas.'
        }
        failure {
            echo 'Hubo errores en la compilacion o en las pruebas.'
        }
    }
}
stage('Pruebas') {
            steps {
                bat 'mvn test'
            }
        }
        stage('Empaquetar') {
            steps {
                bat 'mvn package'
            }
        }
    }
    post {
        success {
            echo 'La compilacion y las pruebas fueron exitosas.'
        }
        failure {
            echo 'Hubo errores en la compilacion o en las pruebas.'
        }
    }
}
